### PR TITLE
Finished Capstone project

### PR DESCRIPTION
**Pull request by digia3d**
link for loom: 
[https://www.loom.com/share/f1b2f54ec37b4f7f859063a722de7b26](URL)

This is the final project of module one.
This project represents the website of a Digital Marketing Agency. 
For this project was used:

- HTML, CSS and JAVASCRIPT.

Parts of the project are added dynamically in JS, and also it was used DOM manipulation.

### CODE REVIEW

**Review by muneebulrehman — COMMENTED** [review]
Hi @digia3d , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not following the flow asked by project requirements, and because I cannot see the changes. Also, you have most of the code for your project in the main branch, which should be empty.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Invalid Code Review Request ❌

Hi @digia3d, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have the correct git-flow which means the pull request should be from (yourbranchname) to main, asked by project requirements, and because I cannot see the changes. Also, you have most of the code for your project in the main branch, which should be empty.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by mikethreels — CHANGES_REQUESTED** [review]
Hi Alex, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that doesn't follow the required gitflow.
The Pull Request should be made from the “feature branch” (in your case the "implement-JS" branch) into the main branch. 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by digia3d** [comment]
> Hi Alex,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> * [ ]  You have submitted a project, that doesn't follow the required gitflow.
>   The Pull Request should be made from the “feature branch” (in your case the "implement-JS" branch) into the main branch.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._


> Hi Alex,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> * [ ]  You have submitted a project, that doesn't follow the required gitflow.
>   The Pull Request should be made from the “feature branch” (in your case the "implement-JS" branch) into the main branch.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

[mikethreels](https://github.com/mikethreels)  I do not understand ? What I should do?

**Comment by mikethreels** [comment]
@digia3d try to close this pull request and open a new one from the feature branch into the main branch, right now you are pulling from the main branch into the future branch which is incorrect

**Comment by digia3d** [comment]
OK. I did that already. Thank you very much.

**Comment by digia3d** [comment]
> Hi @digia3d,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that:
> 
> * Doesn't have anything in the branch. Please submit proper pull request.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by digia3d** [comment]
I must close this pull request because there is some conflict between branches, and the reviewer told me to open a new pull request.

**Pull request closed without merging**
